version: "3.8"

services:
    web:
        build: ./
        command: gunicorn bookCommunity.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/staticfiles
            - uploads_volume:/home/app/web/uploadsfiles
            - ./db.sqlite3:/home/app/web/db.sqlite3
        expose:
            - 8000
        env_file:
            - ./.env
        networks:
            - default
        restart: always
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/app/web/staticfiles
            - uploads_volume:/home/app/web/uploadsfiles
        depends_on:
            - web
        hostname: cafe-book-nginx
        networks:
            - default
            - nginx
        restart: always

volumes:
    static_volume:
    uploads_volume:

networks:
    nginx:
        external: true
